import { colors } from './colors';

export interface Playlist {
  id: string;
  albumId: number;
  title: string;
  color: (typeof colors)[keyof typeof colors];
  cover: string;
  artists: string[];
  creator?: string;
}

export const playlists: Playlist[] = [
  {
    id: '1',
    albumId: 1,
    title: 'Chill Lo-Fi Music',
    color: colors.yellow,
    cover:
      'https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353',
    artists: ['Lish Grooves', 'Track Tribe'],
  },
  {
    id: '2',
    albumId: 2,
    title: 'Lo-Fi Chill Session',
    color: colors.green,
    cover:
      'https://vinyl.lofirecords.com/cdn/shop/files/2amsynth-vinyl.png?v=1693360187',
    artists: ['Unicorn Heads', 'NoMBe'],
  },
  {
    id: '3',
    albumId: 3,
    title: 'Study Session',
    color: colors.rose,
    cover: 'https://f4.bcbits.com/img/a1435058381_65.jpg',
    artists: ['Silent Partner', 'John Paticucci', 'National Sweetheart'],
  },
  {
    id: '4',
    albumId: 4,
    title: 'Blue Note Study Time',
    color: colors.blue,
    cover: 'https://f4.bcbits.com/img/a1962013209_16.jpg',
    artists: ['Vans in Japan', 'Hanu Dixit'],
  },
  {
    id: '5',
    albumId: 5,
    title: 'Dancing in the moonlight',
    color: colors.purple,
    cover: 'https://f4.bcbits.com/img/a2793859494_16.jpg',
    artists: ['Huma-Huma', 'Dougie Wood'],
  },
  {
    id: '6',
    albumId: 6,
    title: 'Cumbia to shake',
    color: colors.orange,
    cover: 'https://f4.bcbits.com/img/a0363760459_16.jpg',
    artists: ['Cumbia Deli', 'Cheel'],
  },
];

export const morePlaylists = playlists.map(item => ({
  ...item,
  id: item.id + '_more',
}));

export const sidebarPlaylists = playlists.map(item => ({
  ...item,
  id: item.id + '_side',
}));

export const allPlaylists = [
  ...playlists,
  ...morePlaylists,
  ...sidebarPlaylists,
];

export interface Song {
  id: number;
  albumId: number;
  title: string;
  image: string;
  artists: string[];
  album: string;
  duration?: number;
  src: string;
}

// TODO: change almbumId to playlistId
export const songs: Song[] = [
  {
    id: 1,
    albumId: 1,
    title: 'Colony',
    image: 'https://picsum.photos/60',
    artists: ['Track Tribe'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Track Tribe/Colony - TrackTribe.mp3',
  },
  {
    id: 2,
    albumId: 1,
    title: 'Helium',
    image: 'https://picsum.photos/60',
    artists: ['Track Tribe'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Track Tribe/Helium - TrackTribe.mp3',
  },
  {
    id: 1,
    albumId: 1,
    title: 'Cosmic',
    image: 'https://picsum.photos/60',
    artists: ['Lish Grooves'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Lish Grooves/Cosmic - Lish Grooves.mp3',
  },
  {
    id: 2,
    albumId: 1,
    title: 'Owls',
    image: 'https://picsum.photos/60',
    artists: ['Lish Grooves'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Lish Grooves/Owls - Lish Grooves.mp3',
  },
  {
    id: 3,
    albumId: 1,
    title: 'The Rainy Road',
    image: 'https://picsum.photos/60',
    artists: ['Lish Grooves'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Lish Grooves/The Rainy Road - Lish Grooves.mp3',
  },
  {
    id: 1,
    albumId: 2,
    title: 'Drifting at 432 Hz',
    image: 'https://picsum.photos/60',
    artists: ['Unicorn Heads'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Unicorn Heads/Drifting at 432 Hz - Unicorn Heads.mp3',
  },
  {
    id: 2,
    albumId: 2,
    title: 'The Urban Symphonia',
    image: 'https://picsum.photos/60',
    artists: ['Unicorn Heads'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Unicorn Heads/The Urban Symphonia - Unicorn Heads.mp3',
  },
  {
    id: 3,
    albumId: 2,
    title: 'Whirlwind Love',
    image: 'https://picsum.photos/60',
    artists: ['Unicorn Heads'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Unicorn Heads/Whirlwind Love - Unicorn Heads.mp3',
  },
  {
    id: 1,
    albumId: 2,
    title: 'Interplanetary Alignment',
    image: 'https://picsum.photos/60',
    artists: ['NoMBe'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/NoMBe/Interplanetary Alignment - NoMBe.mp3',
  },
  {
    id: 2,
    albumId: 2,
    title: 'Take Me Down To The Fashion Show',
    image: 'https://picsum.photos/60',
    artists: ['NoMBe'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/NoMBe/Take Me Down To The Fashion Show - NoMBe.mp3',
  },
  {
    id: 1,
    albumId: 3,
    title: 'Mast',
    image: 'https://picsum.photos/60',
    artists: ['Silent Partner'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Silent Partner/Mast - Silent Partner.mp3',
  },
  {
    id: 1,
    albumId: 3,
    title: 'Gridlock',
    image: 'https://picsum.photos/60',
    artists: ['John Paticucci'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/John Paticucci/Gridlock - John Patitucci.mp3',
  },
  {
    id: 2,
    albumId: 3,
    title: 'Layer Cake',
    image: 'https://picsum.photos/60',
    artists: ['John Paticucci'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/John Paticucci/Layer Cake - John Patitucci.mp3',
  },
  {
    id: 1,
    albumId: 3,
    title: 'A truly dazzling dream',
    image: 'https://picsum.photos/60',
    artists: ['National Sweetheart'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/National Sweetheart/A Truly Dazzling Dream - National Sweetheart.mp3',
  },
  {
    id: 2,
    albumId: 3,
    title: 'Arm Wrestler',
    image: 'https://picsum.photos/60',
    artists: ['National Sweetheart'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/National Sweetheart/Arm Wrestler - National Sweetheart.mp3',
  },
  {
    id: 1,
    albumId: 4,
    title: 'Deep State',
    image: 'https://picsum.photos/60',
    artists: ['Vans in Japan'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Vans in Japan/Deep State - Vans in Japan.mp3',
  },
  {
    id: 2,
    albumId: 4,
    title: 'Sonic Pogo',
    image: 'https://picsum.photos/60',
    artists: ['Vans in Japan'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Vans in Japan/Sonic Pogo - Vans in Japan.mp3',
  },
  {
    id: 1,
    albumId: 4,
    title: 'Streets Of Punjab',
    image: 'https://picsum.photos/60',
    artists: ['Hanu Dixit'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Hanu Dixit/Streets Of Punjab - Hanu Dixit.mp3',
  },
  {
    id: 2,
    albumId: 4,
    title: 'The Urban Groove',
    image: 'https://picsum.photos/60',
    artists: ['Hanu Dixit'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Hanu Dixit/The Urban Groove - Hanu Dixit.mp3',
  },
  {
    id: 1,
    albumId: 5,
    title: 'Satin Sugar',
    image: 'https://picsum.photos/60',
    artists: ['Huma-Huma'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Huma-Huma/Satin Sugar - Huma-Huma.mp3',
  },
  {
    id: 2,
    albumId: 5,
    title: 'Smooth Ridin',
    image: 'https://picsum.photos/60',
    artists: ['Huma-Huma'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Huma-Huma/Smooth Ridin - Huma-Huma.mp3',
  },
  {
    id: 1,
    albumId: 5,
    title: 'Disco Ball',
    image: 'https://picsum.photos/60',
    artists: ['Dougie Wood'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Dougie Wood/Disco Ball - Dougie Wood.mp3',
  },
  {
    id: 2,
    albumId: 5,
    title: 'Drinks On The Bar',
    image: 'https://picsum.photos/60',
    artists: ['Dougie Wood'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Dougie Wood/Drinks On The Bar - Dougie Wood.mp3',
  },
  {
    id: 1,
    albumId: 6,
    title: 'Blue Dream',
    image: 'https://picsum.photos/60',
    artists: ['Cheel'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Cheel/Blue Dream - Cheel.mp3',
  },
  {
    id: 2,
    albumId: 6,
    title: 'Soft Feeling',
    image: 'https://picsum.photos/60',
    artists: ['Cheel'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Cheel/Soft Feeling - Cheel.mp3',
  },
  {
    id: 3,
    albumId: 6,
    title: 'Sunset Dream',
    image: 'https://picsum.photos/60',
    artists: ['Cheel'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Cheel/Sunset Dream - Cheel.mp3',
  },
  {
    id: 4,
    albumId: 6,
    title: 'Blind Memories',
    image: 'https://picsum.photos/60',
    artists: ['Cheel'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Cheel/Blind Memories - Cheel.mp3',
  },
  {
    id: 1,
    albumId: 6,
    title: 'Brisket Taco',
    image: 'https://picsum.photos/60',
    artists: ['Cumbia Deli'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Cumbia Deli/Brisket Taco - Cumbia Deli.mp3',
  },
  {
    id: 2,
    albumId: 6,
    title: 'Correle Carna',
    image: 'https://picsum.photos/60',
    artists: ['Cumbia Deli'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Cumbia Deli/Correle Carna - Cumbia Deli.mp3',
  },
  {
    id: 3,
    albumId: 6,
    title: 'Cumbiera Know It All',
    image: 'https://picsum.photos/60',
    artists: ['Cumbia Deli'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Cumbia Deli/Cumbiera Know It All - Cumbia Deli.mp3',
  },
  {
    id: 4,
    albumId: 6,
    title: 'Day y Noche',
    image: 'https://picsum.photos/60',
    artists: ['Cumbia Deli'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Cumbia Deli/Day y Noche - Cumbia Deli.mp3',
  },
  {
    id: 5,
    albumId: 6,
    title: 'Summer Somewhere In Cuba',
    image: 'https://picsum.photos/60',
    artists: ['Cumbia Deli'],
    album: 'Cumbia to shake',
    duration: undefined,
    src: 'music/Cumbia Deli/Summer Somewhere In Cuba - Cumbia Deli.mp3',
  },
];

// export const songs: Song[] = [
//   {
//     id: 1,
//     albumId: 1,
//     title: 'Moonlit Walk',
//    'https://picsum.photos/60'v=1680526353`,
//     artists: ['LoFi Dreamer'],
//     album: 'Chill Lo-Fi Music',
//     duration: '3:60',
//   },
//   {
//     id: 2,
//     albumId: 1,
//     title: 'Coffee Daze',
//     image: `https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353`,
//     artists: ['LoFi Dreamer'],
//     album: 'Chill Lo-Fi Music',
//     duration: '4:07',
//   },
//   {
//     id: 3,
//     albumId: 1,
//     title: 'Skyline Serenade',
//     image: `https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353`,
//     artists: ['LoFi Dreamer'],
//     album: 'Chill Lo-Fi Music',
//     duration: '3:50',
//   },
//   {
//     id: 4,
//     albumId: 1,
//     title: 'Urban Echoes',
//     image: `https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353`,
//     artists: ['LoFi Dreamer'],
//     album: 'Chill Lo-Fi Music',
//     duration: '3:60',
//   },
//   {
//     id: 5,
//     albumId: 1,
//     title: "Night's End",
//     image: `https://vinyl.lofirecords.com/cdn/shop/products/VINYL_MORNING_COFFEE_4-min.png?v=1680526353`,
//     artists: ['LoFi Dreamer'],
//     album: 'Chill Lo-Fi Music',
//     duration: '4:20',
//   },
//   {
//     id: 1,
//     albumId: 2,
//     title: 'Silent Rain',
//     image: `https://vinyl.lofirecords.com/cdn/shop/files/2amsynth-vinyl.png?v=1693360187`,
//     artists: ['Urban Nocturne'],
//     album: 'Midnight Tales',
//     duration: '3:60',
//   },
//   {
//     id: 2,
//     albumId: 2,
//     title: 'Lost Pages',
//     image: `https://vinyl.lofirecords.com/cdn/shop/files/2amsynth-vinyl.png?v=1693360187`,
//     artists: ['Urban Nocturne'],
//     album: 'Midnight Tales',
//     duration: '3:20',
//   },
//   {
//     id: 3,
//     albumId: 2,
//     title: 'Midnight Tales',
//     image: `https://vinyl.lofirecords.com/cdn/shop/files/2amsynth-vinyl.png?v=1693360187`,
//     artists: ['Urban Nocturne'],
//     album: 'Midnight Tales',
//     duration: '3:50',
//   },
//   {
//     id: 4,
//     albumId: 2,
//     title: 'City Lights',
//     image: `https://vinyl.lofirecords.com/cdn/shop/files/2amsynth-vinyl.png?v=1693360187`,
//     artists: ['Urban Nocturne'],
//     album: 'Midnight Tales',
//     duration: '3:60',
//   },
//   {
//     id: 5,
//     albumId: 2,
//     title: 'Night Drive',
//     image: `https://vinyl.lofirecords.com/cdn/shop/files/2amsynth-vinyl.png?v=1693360187`,
//     artists: ['Urban Nocturne'],
//     album: 'Midnight Tales',
//     duration: '4:20',
//   },
//   {
//     id: 1,
//     albumId: 3,
//     title: 'Lunar',
//     image: `https://f4.bcbits.com/img/a1435058381_65.jpg`,
//     artists: ['Tenno'],
//     album: 'Study Session',
//     duration: '3:60',
//   },
//   {
//     id: 2,
//     albumId: 3,
//     title: 'Go go go!',
//     image: `https://f4.bcbits.com/img/a1435058381_65.jpg`,
//     artists: ['Tenno'],
//     album: 'Study Session',
//     duration: '3:20',
//   },
//   {
//     id: 3,
//     albumId: 3,
//     title: 'Keep focus!',
//     image: `https://f4.bcbits.com/img/a1435058381_65.jpg`,
//     artists: ['Tenno'],
//     album: 'Study Session',
//     duration: '2:60',
//   },
//   {
//     id: 4,
//     albumId: 3,
//     title: 'JavaScript is the way',
//     image: `https://f4.bcbits.com/img/a1435058381_65.jpg`,
//     artists: ['Tenno'],
//     album: 'Study Session',
//     duration: '3:10',
//   },
//   {
//     id: 5,
//     albumId: 3,
//     title: 'No more TypeScript for me',
//     image: `https://f4.bcbits.com/img/a1435058381_65.jpg`,
//     artists: ['Tenno'],
//     album: 'Study Session',
//     duration: '2:10',
//   },
//   {
//     id: 1,
//     albumId: 4,
//     title: 'Lunar',
//     image: 'public/https://f4.bcbits.com/img/a1962013209_16.jpg',
//     artists: ['Tenno'],
//     album: 'Study Session',
//     duration: '3:60',
//   },
//   {
//     id: 2,
//     albumId: 4,
//     title: 'Go go go!',
//     image: 'public/https://f4.bcbits.com/img/a1962013209_16.jpg',
//     artists: ['Tenno'],
//     album: 'Study Session',
//     duration: '3:20',
//   },
//   {
//     id: 3,
//     albumId: 4,
//     title: 'Keep focus!',
//     image: 'public/https://f4.bcbits.com/img/a1962013209_16.jpg',
//     artists: ['Tenno'],
//     album: 'Study Session',
//     duration: '2:60',
//   },
//   {
//     id: 4,
//     albumId: 4,
//     title: 'JavaScript is the way',
//     image: 'https://f4.bcbits.com/img/a1962013209_16.jpg',
//     artists: ['Tenno'],
//     album: 'Study Session',
//     duration: '3:10',
//   },
//   {
//     id: 5,
//     albumId: 4,
//     title: 'No more TypeScript for me',
//     image: 'https://f4.bcbits.com/img/a1962013209_16.jpg',
//     artists: ['Tenno'],
//     album: 'Study Session',
//     duration: '2:10',
//   },
//   {
//     id: 1,
//     albumId: 5,
//     title: 'Moonlit Walk',
//     image: 'https://f4.bcbits.com/img/a2793859494_16.jpg',
//     artists: ['LoFi Dreamer'],
//     album: 'Chill Lo-Fi Music',
//     duration: '3:60',
//   },
//   {
//     id: 2,
//     albumId: 5,
//     title: 'Coffee Daze',
//     image: 'https://f4.bcbits.com/img/a2793859494_16.jpg',
//     artists: ['LoFi Dreamer'],
//     album: 'Chill Lo-Fi Music',
//     duration: '4:07',
//   },
//   {
//     id: 3,
//     albumId: 5,
//     title: 'Skyline Serenade',
//     image: 'https://f4.bcbits.com/img/a2793859494_16.jpg',
//     artists: ['LoFi Dreamer'],
//     album: 'Chill Lo-Fi Music',
//     duration: '3:50',
//   },
//   {
//     id: 4,
//     albumId: 5,
//     title: 'Urban Echoes',
//     image: 'https://f4.bcbits.com/img/a2793859494_16.jpg',
//     artists: ['LoFi Dreamer'],
//     album: 'Chill Lo-Fi Music',
//     duration: '3:60',
//   },
//   {
//     id: 5,
//     albumId: 5,
//     title: "Night's End",
//     image: 'https://f4.bcbits.com/img/a2793859494_16.jpg',
//     artists: ['LoFi Dreamer'],
//     album: 'Chill Lo-Fi Music',
//     duration: '4:20',
//   },
// ];
